# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ratelimitter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ratelimitter.proto',
  package='ratelimitter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12ratelimitter.proto\x12\x0cratelimitter\":\n\x10RateLimitRequest\x12\x0e\n\x06UserID\x18\x01 \x01(\t\x12\x16\n\x0ePerMinuteLimit\x18\x02 \x01(\x05\"D\n\x11RateLimitResponse\x12\x18\n\x10\x43urMinuteCounter\x18\x01 \x01(\x05\x12\x15\n\rExceededLimit\x18\x02 \x01(\x08\x32h\n\x10RateLimitService\x12T\n\x0fShouldRateLimit\x12\x1e.ratelimitter.RateLimitRequest\x1a\x1f.ratelimitter.RateLimitResponse\"\x00\x62\x06proto3')
)




_RATELIMITREQUEST = _descriptor.Descriptor(
  name='RateLimitRequest',
  full_name='ratelimitter.RateLimitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='ratelimitter.RateLimitRequest.UserID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PerMinuteLimit', full_name='ratelimitter.RateLimitRequest.PerMinuteLimit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=94,
)


_RATELIMITRESPONSE = _descriptor.Descriptor(
  name='RateLimitResponse',
  full_name='ratelimitter.RateLimitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CurMinuteCounter', full_name='ratelimitter.RateLimitResponse.CurMinuteCounter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ExceededLimit', full_name='ratelimitter.RateLimitResponse.ExceededLimit', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['RateLimitRequest'] = _RATELIMITREQUEST
DESCRIPTOR.message_types_by_name['RateLimitResponse'] = _RATELIMITRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RateLimitRequest = _reflection.GeneratedProtocolMessageType('RateLimitRequest', (_message.Message,), {
  'DESCRIPTOR' : _RATELIMITREQUEST,
  '__module__' : 'ratelimitter_pb2'
  # @@protoc_insertion_point(class_scope:ratelimitter.RateLimitRequest)
  })
_sym_db.RegisterMessage(RateLimitRequest)

RateLimitResponse = _reflection.GeneratedProtocolMessageType('RateLimitResponse', (_message.Message,), {
  'DESCRIPTOR' : _RATELIMITRESPONSE,
  '__module__' : 'ratelimitter_pb2'
  # @@protoc_insertion_point(class_scope:ratelimitter.RateLimitResponse)
  })
_sym_db.RegisterMessage(RateLimitResponse)



_RATELIMITSERVICE = _descriptor.ServiceDescriptor(
  name='RateLimitService',
  full_name='ratelimitter.RateLimitService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=166,
  serialized_end=270,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShouldRateLimit',
    full_name='ratelimitter.RateLimitService.ShouldRateLimit',
    index=0,
    containing_service=None,
    input_type=_RATELIMITREQUEST,
    output_type=_RATELIMITRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RATELIMITSERVICE)

DESCRIPTOR.services_by_name['RateLimitService'] = _RATELIMITSERVICE

# @@protoc_insertion_point(module_scope)
